from services.nlp_service import extract_skills_from_text
from services.gap_analysis import calculate_gap
from services.recommendation_engine import get_recommendations
from services.scoring_service import score_candidate, get_all_candidates_scored
from services.email_service import send_welcome_email, send_free_course_alert, send_verification_email
